In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
pd.read_csv('multipleChoiceResponses.csv', encoding="ISO-8859-1", low_memory=False)

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
0,"Non-binary, genderqueer, or gender non-conforming",NaN,NaN,Employed full-time,NaN,NaN,Yes,NaN,DBA/Database Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Female,United States,30.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Somewhat important,NaN,NaN
2,Male,Canada,28.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important
3,Male,United States,56.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Operations Research Practitioner,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,Taiwan,38.0,Employed full-time,NaN,NaN,Yes,NaN,Computer Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Male,Brazil,46.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Computer Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Female,India,22.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,Very Important,Somewhat important,Very Important,Somewhat important,Somewhat important,Not important,Very Important,Very Important,Somewhat important,Somewhat important
8,Female,Australia,43.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Male,Russia,33.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Female,Russia,20.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,Somewhat important,Very Important,Very Important,Somewhat important,Very Important,Somewhat important,Very Important,Very Important,Somewhat important,Somewhat important
11,Male,India,27.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Male,Brazil,26.0,Employed full-time,NaN,NaN,No,Yes,Engineer,Fine,...,Very Important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
13,Male,Netherlands,54.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Male,Taiwan,26.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Male,United States,58.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Male,Italy,58.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Male,United Kingdom,24.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Male,United States,26.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important
19,Male,Brazil,39.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Not important,NaN,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Not important,Not important,Not important
20,Male,United States,49.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
21,Male,United States,25.0,Employed part-time,NaN,NaN,Yes,NaN,Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Male,Czech Republic,21.0,Employed part-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Male,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Male,Russia,22.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Male,Netherlands,51.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Male,Colombia,34.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Male,Germany,41.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Female,Canada,32.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,Very Important,Somewhat important,Somewhat important,Not important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Very Important
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16686,Male,Finland,38.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16687,Male,Malaysia,55.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Business Analyst,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16688,Female,Iran,22.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Statistician,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16689,Female,Israel,42.0,Employed part-time,NaN,NaN,Yes,NaN,Programmer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16690,Male,Germany,32.0,Employed part-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16691,Male,Poland,39.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16692,Male,Norway,34.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16693,Male,India,28.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16694,Male,United States,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16695,Male,India,24.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16696,Male,People 's Republic of China,24.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16697,Male,Other,32.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16698,Male,Australia,NaN,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16699,Male,People 's Republic of China,30.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16700,Male,South Korea,45.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16701,Male,India,33.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16702,Male,Australia,25.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16703,Male,Other,25.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16704,Male,Indonesia,26.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,Male,India,28.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16706,Male,Australia,NaN,Employed full-time,NaN,NaN,Yes,NaN,Other,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16707,Female,Indonesia,30.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16708,Male,Indonesia,21.0,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16709,Male,People 's Republic of China,34.0,Employed full-time,NaN,NaN,Yes,NaN,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16710,Male,People 's Republic of China,23.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16711,Female,Other,24.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16712,Male,Indonesia,25.0,Employed full-time,NaN,NaN,Yes,NaN,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16713,Female,Taiwan,25.0,Employed part-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16714,Female,Singapore,16.0,I prefer not to say,Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16715,Male,Japan,27.0,Employed full-time,NaN,NaN,No,Yes,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_mcr = pd.read_csv('multipleChoiceResponses.csv', encoding="ISO-8859-1", low_memory=False)

In [4]:
df_mcr['Country'].value_counts()

United States                  4197
India                          2704
Other                          1023
Russia                          578
United Kingdom                  535
People 's Republic of China     471
Brazil                          465
Germany                         460
France                          442
Canada                          440
Australia                       421
Spain                           320
Japan                           277
Taiwan                          254
Italy                           238
Netherlands                     205
Ukraine                         196
South Korea                     194
Poland                          184
Singapore                       184
Pakistan                        161
Turkey                          144
Indonesia                       131
Switzerland                     129
South Africa                    127
Mexico                          126
Colombia                        113
Iran                            112
Israel                          105
Ireland                          94
Portugal                         93
Argentina                        92
Belgium                          91
Sweden                           89
Philippines                      84
Greece                           81
Malaysia                         79
Denmark                          78
New Zealand                      74
Nigeria                          73
Vietnam                          71
Republic of China                67
Finland                          67
Egypt                            66
Hungary                          66
Hong Kong                        65
Kenya                            59
Romania                          59
Belarus                          54
Czech Republic                   53
Norway                           53
Chile                            51
Name: Country, dtype: int64

In [5]:
df_mcr[df_mcr['Country'] == 'United States']

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
1,Female,United States,30.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Somewhat important,NaN,NaN
3,Male,United States,56.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Operations Research Practitioner,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Computer Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Male,United States,58.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Male,United States,26.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important
20,Male,United States,49.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
21,Male,United States,25.0,Employed part-time,NaN,NaN,Yes,NaN,Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Male,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Male,United States,43.0,Retired,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Operations Research Practitioner,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Male,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Female,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Not important,Somewhat important,Somewhat important
48,Male,United States,27.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Male,United States,63.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Male,United States,32.0,Employed full-time,NaN,NaN,Yes,NaN,Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Male,United States,40.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Male,United States,25.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Male,United States,47.0,"Not employed, and not looking for work",No,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Female,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Female,United States,39.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Male,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Female,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,Female,United States,36.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Very Important,Not important,Somewhat important,Somewhat important,Not important,Somewhat important
109,Male,United States,23.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Male,United States,59.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Female,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16498,Male,United States,70.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16501,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16504,Female,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Machine Learning Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16508,Male,United States,57.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16511,Female,United States,26.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16520,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16523,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16525,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16533,Male,United States,42.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16536,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16550,Male,United States,47.0,Employed part-time,NaN,NaN,No,Yes,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16553,Female,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16555,Female,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16569,Male,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16578,Male,United States,59.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16592,Male,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16594,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16598,Male,United States,34.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16600,Male,United States,20.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16604,Male,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16611,Male,United States,43.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16614,Female,United States,25.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16618,Female,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16620,Female,United States,NaN,I prefer not to say,Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16625,Male,United States,39.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16630,Male,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Statistician,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16631,Female,United States,41.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16668,Male,United States,24.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16675,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16694,Male,United States,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
US_Data_Scientist = df_mcr[df_mcr['Country'] == 'United States']

In [7]:
US_Data_Scientist

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
1,Female,United States,30.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Somewhat important,NaN,NaN
3,Male,United States,56.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Operations Research Practitioner,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Computer Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Male,United States,58.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Male,United States,26.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important
20,Male,United States,49.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
21,Male,United States,25.0,Employed part-time,NaN,NaN,Yes,NaN,Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Male,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Male,United States,43.0,Retired,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Operations Research Practitioner,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Male,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Female,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Not important,Somewhat important,Somewhat important
48,Male,United States,27.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Male,United States,63.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Male,United States,32.0,Employed full-time,NaN,NaN,Yes,NaN,Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Male,United States,40.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Male,United States,25.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Male,United States,47.0,"Not employed, and not looking for work",No,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Female,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Female,United States,39.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Male,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Female,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,Female,United States,36.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Very Important,Not important,Somewhat important,Somewhat important,Not important,Somewhat important
109,Male,United States,23.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Male,United States,59.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Female,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16498,Male,United States,70.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16501,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16504,Female,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Machine Learning Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16508,Male,United States,57.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16511,Female,United States,26.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16520,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16523,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16525,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16533,Male,United States,42.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16536,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16550,Male,United States,47.0,Employed part-time,NaN,NaN,No,Yes,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16553,Female,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16555,Female,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16569,Male,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16578,Male,United States,59.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16592,Male,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16594,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16598,Male,United States,34.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16600,Male,United States,20.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16604,Male,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16611,Male,United States,43.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16614,Female,United States,25.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16618,Female,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16620,Female,United States,NaN,I prefer not to say,Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16625,Male,United States,39.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16630,Male,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Statistician,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16631,Female,United States,41.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16668,Male,United States,24.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16675,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16694,Male,United States,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# pd.DataFrame(some_thing).to_csv('filepath.csv', index=False)
# US_Data_Scientist.to_csv('filepath.csv', index=False)

In [9]:
# pd.Series(list).value_counts()

In [10]:
# pd.DataFrame(some_thing).to_csv('filepath.csv', index=False)
US_Data_Scientist.to_csv('USData_Scientist.csv', index=False)

In [11]:
pd.read_csv('USData_Scientist.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (124) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
0,Female,United States,30.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Somewhat important,NaN,NaN
1,Male,United States,56.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Operations Research Practitioner,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Computer Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Male,United States,58.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,United States,26.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important,Very Important
5,Male,United States,49.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
6,Male,United States,25.0,Employed part-time,NaN,NaN,Yes,NaN,Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Male,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Male,United States,43.0,Retired,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Male,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Operations Research Practitioner,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Male,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Female,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Not important,Somewhat important,Somewhat important
14,Male,United States,27.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Male,United States,63.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Male,United States,32.0,Employed full-time,NaN,NaN,Yes,NaN,Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Male,United States,40.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Male,United States,25.0,Employed full-time,NaN,NaN,Yes,NaN,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Male,United States,47.0,"Not employed, and not looking for work",No,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Female,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Female,United States,39.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Male,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Female,United States,30.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Female,United States,36.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,Very Important,Very Important,Very Important,Somewhat important,Very Important,Not important,Somewhat important,Somewhat important,Not important,Somewhat important
27,Male,United States,23.0,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Male,United States,59.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Female,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5672,Male,United States,70.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5673,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5674,Female,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Machine Learning Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5675,Male,United States,57.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5676,Female,United States,26.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5677,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Predictive Modeler,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5678,Male,United States,35.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5679,Male,United States,50.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5680,Male,United States,42.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5681,Female,United States,NaN,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5682,Male,United States,47.0,Employed part-time,NaN,NaN,No,Yes,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5683,Female,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5684,Female,United States,33.0,Employed full-time,NaN,NaN,Yes,NaN,Data Scientist,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5685,Male,United States,22.0,"Not employed, and not looking for work",Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5686,Male,United States,59.0,Employed full-time,NaN,NaN,Yes,NaN,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5687,Male,United States,26.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5688,Male,United States,29.0,Employed full-time,NaN,NaN,Yes,NaN,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5689,Male,United States,34.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5690,Male,United States,20.0,Employed full-time,NaN,NaN,Yes,NaN,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5691,Male,United States,31.0,Employed full-time,NaN,NaN,Yes,NaN,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5692,Male,United States,43.0,Employed full-time,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5693,Female,United States,25.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5694,Female,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5695,Female,United States,NaN,I prefer not to say,Yes,"Yes, I'm focused on learning mostly data scien...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5696,Male,United States,39.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5697,Male,United States,27.0,Employed part-time,NaN,NaN,Yes,NaN,Statistician,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5698,Female,United States,41.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5699,Male,United States,24.0,"Not employed, and not looking for work",Yes,"Yes, but data science is a small part of what ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5700,Male,United States,23.0,Employed full-time,NaN,NaN,Yes,NaN,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5701,Male,United States,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,Yes,NaN,Data Scientist,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_US = pd.read_csv('USData_Scientist.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (124) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
df_US.shape

(5702, 228)

In [14]:
df_US.isnull().sum()

GenderSelect                                 10
Country                                       8
Age                                         102
EmploymentStatus                             10
StudentStatus                              5476
LearningDataScience                        5475
CodeWriter                                  740
CareerSwitcher                             5048
CurrentJobTitleSelect                      1080
TitleFit                                   1151
CurrentEmployerType                        1122
MLToolNextYearSelect                       1417
MLMethodNextYearSelect                     1448
LanguageRecommendationSelect               1408
PublicDatasetsSelect                       1470
LearningPlatformSelect                     1322
LearningPlatformUsefulnessArxiv            3611
LearningPlatformUsefulnessBlogs            2929
LearningPlatformUsefulnessCollege          4738
LearningPlatformUsefulnessCompany          3865
LearningPlatformUsefulnessConferences      5051
LearningPlatformUsefulnessFriends          5242
LearningPlatformUsefulnessKaggle           2565
LearningPlatformUsefulnessNewsletters      3927
LearningPlatformUsefulnessCommunities      5405
LearningPlatformUsefulnessDocumentation    5050
LearningPlatformUsefulnessCourses          4167
LearningPlatformUsefulnessProjects         4192
LearningPlatformUsefulnessPodcasts         5227
LearningPlatformUsefulnessSO               2571
                                           ...
WorkMLTeamSeatSelect                       2313
WorkDatasets                               3529
WorkDatasetsChallenge                      4908
WorkDataStorage                            3853
WorkDataSharing                            3848
WorkDataSourcing                           5567
WorkCodeSharing                            3944
RemoteWork                                 3937
CompensationAmount                         4162
CompensationCurrency                       4455
SalaryChange                               3874
JobSatisfaction                            3800
JobSearchResource                          4931
JobHuntTime                                4908
JobFactorLearning                          4938
JobFactorSalary                            4944
JobFactorOffice                            4949
JobFactorLanguages                         4950
JobFactorCommute                           4945
JobFactorManagement                        4954
JobFactorExperienceLevel                   4954
JobFactorDepartment                        4953
JobFactorTitle                             4957
JobFactorCompanyFunding                    4957
JobFactorImpact                            4959
JobFactorRemote                            4956
JobFactorIndustry                          4954
JobFactorLeaderReputation                  4960
JobFactorDiversity                         4957
JobFactorPublishingOpportunity             4959
Length: 228, dtype: int64

In [24]:
df_US[df_US['CareerSwitcher'] == 'No']

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
23,Male,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Male,United States,50.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Male,United States,53.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Male,United States,59.0,Retired,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Female,United States,52.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Male,United States,28.0,Employed part-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Male,United States,34.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Female,United States,18.0,Employed part-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Male,United States,23.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Male,United States,23.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Male,United States,22.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,Female,United States,42.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Male,United States,35.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,Female,United States,27.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,Female,United States,24.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,Male,United States,19.0,Employed part-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,Male,United States,59.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,Male,United States,68.0,Retired,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,Female,United States,35.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,Male,United States,30.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,Male,United States,47.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,Male,United States,48.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,Female,United States,47.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,Male,United States,24.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,Male,United States,35.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Male,United States,28.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,Female,United States,19.0,Employed part-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,Female,United States,35.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571,Female,United States,30.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
584,Male,United States,72.0,Retired,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4891,Male,United States,47.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4901,Male,United States,30.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4935,Male,United States,37.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4978,Male,United States,25.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4983,Male,United States,69.0,Retired,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4995,Female,United States,53.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5013,Male,United States,33.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5020,Male,United States,25.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5028,Male,United States,34.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5048,Male,United States,48.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5069,Male,United States,28.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5076,Male,United States,NaN,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5087,Male,United States,31.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5091,Male,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5096,Male,United States,32.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5098,Male,United States,34.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5137,Male,United States,42.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5153,Male,United States,60.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5173,Male,United States,24.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5193,Male,United States,32.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5235,Male,United States,31.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5320,Female,United States,52.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,Male,United States,NaN,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5375,Male,United States,34.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5435,Female,United States,33.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5589,Male,United States,63.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5594,Male,United States,21.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5595,Male,United States,40.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5610,Male,United States,39.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5694,Female,United States,44.0,Employed full-time,NaN,NaN,No,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_US[df_US['CareerSwitcher'] == 'Yes'].count()

GenderSelect                               406
Country                                    407
Age                                        400
EmploymentStatus                           407
StudentStatus                                0
LearningDataScience                          0
CodeWriter                                 407
CareerSwitcher                             407
CurrentJobTitleSelect                      385
TitleFit                                   376
CurrentEmployerType                        381
MLToolNextYearSelect                       349
MLMethodNextYearSelect                     337
LanguageRecommendationSelect               338
PublicDatasetsSelect                       336
LearningPlatformSelect                     343
LearningPlatformUsefulnessArxiv             34
LearningPlatformUsefulnessBlogs            127
LearningPlatformUsefulnessCollege          101
LearningPlatformUsefulnessCompany           16
LearningPlatformUsefulnessConferences       31
LearningPlatformUsefulnessFriends           34
LearningPlatformUsefulnessKaggle           197
LearningPlatformUsefulnessNewsletters       33
LearningPlatformUsefulnessCommunities       24
LearningPlatformUsefulnessDocumentation     41
LearningPlatformUsefulnessCourses          204
LearningPlatformUsefulnessProjects         147
LearningPlatformUsefulnessPodcasts          55
LearningPlatformUsefulnessSO               143
                                          ...
WorkMLTeamSeatSelect                         0
WorkDatasets                                 0
WorkDatasetsChallenge                        0
WorkDataStorage                              0
WorkDataSharing                              0
WorkDataSourcing                             0
WorkCodeSharing                              0
RemoteWork                                   0
CompensationAmount                           0
CompensationCurrency                         0
SalaryChange                                 0
JobSatisfaction                              0
JobSearchResource                          273
JobHuntTime                                301
JobFactorLearning                          286
JobFactorSalary                            286
JobFactorOffice                            284
JobFactorLanguages                         283
JobFactorCommute                           284
JobFactorManagement                        281
JobFactorExperienceLevel                   283
JobFactorDepartment                        282
JobFactorTitle                             283
JobFactorCompanyFunding                    280
JobFactorImpact                            282
JobFactorRemote                            281
JobFactorIndustry                          283
JobFactorLeaderReputation                  281
JobFactorDiversity                         281
JobFactorPublishingOpportunity             281
Length: 228, dtype: int64

In [17]:
df_US[df_US['CareerSwitcher'] == 'Yes']['LearningCategorySelftTaught']

5        20.0
33       50.0
38      100.0
39       45.0
40       30.0
48       20.0
55       30.0
82       40.0
87       95.0
91       50.0
92       50.0
96        0.0
98       10.0
101      10.0
106       0.0
110      33.0
118      90.0
119      30.0
129      15.0
134      50.0
168      30.0
183      15.0
188      10.0
189      60.0
199       0.0
202       0.0
209      50.0
216       0.0
239      20.0
248      40.0
        ...
5377     50.0
5399    100.0
5420     50.0
5433      0.0
5437     10.0
5462     20.0
5470      0.0
5474     20.0
5483     40.0
5494      NaN
5507     40.0
5520      NaN
5528     85.0
5534      NaN
5551     20.0
5571     50.0
5578      NaN
5579     20.0
5580     30.0
5590      NaN
5596      NaN
5616      NaN
5631      NaN
5641      0.0
5656      NaN
5667      NaN
5669      NaN
5676      NaN
5682     25.0
5698      0.0
Name: LearningCategorySelftTaught, Length: 407, dtype: float64

In [18]:
careerswitcher = df_US[df_US['CareerSwitcher'] == 'Yes']

In [19]:
careerswitcher.sum()

LearningCategorySelftTaught      11317.0
LearningCategoryOnlineCourses    14185.0
LearningCategoryWork              1867.0
LearningCategoryUniversity        7040.0
LearningCategoryKaggle            1611.0
LearningCategoryOther              680.0
TimeGatheringData                    0.0
TimeModelBuilding                    0.0
TimeProduction                       0.0
TimeVisualizing                      0.0
TimeFindingInsights                  0.0
TimeOtherSelect                      0.0
dtype: float64

In [20]:
 careerswitcher.to_csv('careerswitcher.csv', index=False)

In [21]:
df_US[df_US['CareerSwitcher'] == 'Yes'].count()

GenderSelect                               406
Country                                    407
Age                                        400
EmploymentStatus                           407
StudentStatus                                0
LearningDataScience                          0
CodeWriter                                 407
CareerSwitcher                             407
CurrentJobTitleSelect                      385
TitleFit                                   376
CurrentEmployerType                        381
MLToolNextYearSelect                       349
MLMethodNextYearSelect                     337
LanguageRecommendationSelect               338
PublicDatasetsSelect                       336
LearningPlatformSelect                     343
LearningPlatformUsefulnessArxiv             34
LearningPlatformUsefulnessBlogs            127
LearningPlatformUsefulnessCollege          101
LearningPlatformUsefulnessCompany           16
LearningPlatformUsefulnessConferences       31
LearningPlatformUsefulnessFriends           34
LearningPlatformUsefulnessKaggle           197
LearningPlatformUsefulnessNewsletters       33
LearningPlatformUsefulnessCommunities       24
LearningPlatformUsefulnessDocumentation     41
LearningPlatformUsefulnessCourses          204
LearningPlatformUsefulnessProjects         147
LearningPlatformUsefulnessPodcasts          55
LearningPlatformUsefulnessSO               143
                                          ...
WorkMLTeamSeatSelect                         0
WorkDatasets                                 0
WorkDatasetsChallenge                        0
WorkDataStorage                              0
WorkDataSharing                              0
WorkDataSourcing                             0
WorkCodeSharing                              0
RemoteWork                                   0
CompensationAmount                           0
CompensationCurrency                         0
SalaryChange                                 0
JobSatisfaction                              0
JobSearchResource                          273
JobHuntTime                                301
JobFactorLearning                          286
JobFactorSalary                            286
JobFactorOffice                            284
JobFactorLanguages                         283
JobFactorCommute                           284
JobFactorManagement                        281
JobFactorExperienceLevel                   283
JobFactorDepartment                        282
JobFactorTitle                             283
JobFactorCompanyFunding                    280
JobFactorImpact                            282
JobFactorRemote                            281
JobFactorIndustry                          283
JobFactorLeaderReputation                  281
JobFactorDiversity                         281
JobFactorPublishingOpportunity             281
Length: 228, dtype: int64

In [22]:
careerswitcher

,GenderSelect,Country,Age,EmploymentStatus,StudentStatus,LearningDataScience,CodeWriter,CareerSwitcher,CurrentJobTitleSelect,TitleFit,...,JobFactorExperienceLevel,JobFactorDepartment,JobFactorTitle,JobFactorCompanyFunding,JobFactorImpact,JobFactorRemote,JobFactorIndustry,JobFactorLeaderReputation,JobFactorDiversity,JobFactorPublishingOpportunity
5,Male,United States,49.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
33,Female,United States,20.0,Employed part-time,NaN,NaN,No,Yes,Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Male,United States,31.0,Employed full-time,NaN,NaN,No,Yes,Business Analyst,Fine,...,Very Important,Very Important,Very Important,NaN,NaN,NaN,NaN,NaN,NaN,Very Important
39,Male,United States,35.0,Employed full-time,NaN,NaN,No,Yes,Engineer,Fine,...,Not important,Not important,Not important,Not important,Not important,Not important,Not important,Not important,Not important,Not important
40,Male,United States,20.0,Employed full-time,NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,Somewhat important,Very Important,Not important,Somewhat important,Not important,Not important,Somewhat important,Very Important,Not important,Very Important
48,Female,United States,21.0,Employed part-time,NaN,NaN,No,Yes,Other,Fine,...,Very Important,Somewhat important,Somewhat important,Not important,Somewhat important,Not important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
55,Male,United States,19.0,Employed part-time,NaN,NaN,No,Yes,Other,Fine,...,Very Important,Somewhat important,Somewhat important,Somewhat important,Not important,Not important,Very Important,Somewhat important,Not important,Somewhat important
82,Male,United States,27.0,Employed full-time,NaN,NaN,No,Yes,Programmer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Male,United States,38.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Male,United States,30.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Perfectly,...,Somewhat important,Somewhat important,Very Important,Somewhat important,Very Important,Not important,Somewhat important,Somewhat important,Somewhat important,Very Important
92,Male,United States,24.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,Somewhat important,Somewhat important,Somewhat important,Very Important,Very Important,Somewhat important,Somewhat important,Somewhat important,Very Important,Very Important
96,Female,United States,29.0,Employed full-time,NaN,NaN,No,Yes,DBA/Database Engineer,Fine,...,Very Important,Not important,Somewhat important,Not important,Not important,Not important,Somewhat important,Not important,Not important,Not important
98,Female,United States,18.0,Employed part-time,NaN,NaN,No,Yes,Other,Perfectly,...,Somewhat important,Somewhat important,Very Important,Somewhat important,Somewhat important,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important
101,Male,United States,41.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,Very Important,Not important,Somewhat important,Not important,Very Important,Not important,Somewhat important,Not important,Very Important,Not important
106,Male,United States,53.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Other,Perfectly,...,Very Important,Very Important,Very Important,Not important,Not important,Somewhat important,Somewhat important,Not important,Not important,Not important
110,Male,United States,23.0,Employed part-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,Somewhat important,Very Important,Very Important,Not important,Somewhat important,Not important,Not important,Somewhat important,Not important,Very Important
118,Male,United States,42.0,Employed full-time,NaN,NaN,No,Yes,Business Analyst,Poorly,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Very Important,Somewhat important,Somewhat important,Not important,Somewhat important
119,Male,United States,24.0,Employed part-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,Somewhat important,Somewhat important,Somewhat important,Not important,Somewhat important,Not important,Not important,Not important,Somewhat important,Not important
129,Male,United States,36.0,Employed full-time,NaN,NaN,No,Yes,Business Analyst,Fine,...,Somewhat important,Somewhat important,Very Important,Very Important,Very Important,Not important,Somewhat important,Somewhat important,Very Important,Very Important
134,Male,United States,23.0,Employed part-time,NaN,NaN,No,Yes,Researcher,Fine,...,Very Important,Not important,Not important,Not important,Not important,Not important,Not important,Not important,Not important,Not important
168,Male,United States,42.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Programmer,Fine,...,Somewhat important,Somewhat important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Somewhat important
183,Male,United States,19.0,Employed full-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,Male,United States,25.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Perfectly,...,Not important,Not important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Somewhat important,Somewhat important,Not important
189,Female,United States,51.0,Employed full-time,NaN,NaN,No,Yes,DBA/Database Engineer,Fine,...,Very Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Very Important,Not important,Somewhat important,Not important,Not important
199,Female,United States,31.0,Employed full-time,NaN,NaN,No,Yes,Data Analyst,Fine,...,Very Important,Somewhat important,Not important,Not important,Somewhat important,Very Important,Very Important,Somewhat important,Very Important,Very Important
202,Male,United States,69.0,Employed full-time,NaN,NaN,No,Yes,Other,Poorly,...,Very Important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Very Important,Somewhat important,Not important,Not important
209,Male,United States,21.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,Male,United States,22.0,Employed part-time,NaN,NaN,No,Yes,Other,Fine,...,Very Important,Not important,Somewhat important,Not important,Not important,Not important,Very Important,Not important,Not important,Not important
239,Female,United States,40.0,Employed full-time,NaN,NaN,No,Yes,Other,Poorly,...,Somewhat important,Not important,Not important,Not important,Not important,Very Important,Not important,Not important,Not important,Not important
248,Male,United States,48.0,"Independent contractor, freelancer, or self-em...",NaN,NaN,No,Yes,Engineer,Fine,...,Somewhat important,Not important,Not important,Somewhat important,Somewhat important,Very Important,Very Important,Very Important,Very Important,Somewhat important
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5377,Male,United States,NaN,Employed full-time,NaN,NaN,No,Yes,Other,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5399,Female,United States,46.0,Employed full-time,NaN,NaN,No,Yes,DBA/Database Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,Male,United States,42.0,Employed full-time,NaN,NaN,No,Yes,Business Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,Male,United States,15.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5437,Male,United States,50.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5462,Male,United States,50.0,Employed full-time,NaN,NaN,No,Yes,Other,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5470,Male,United States,34.0,Employed full-time,NaN,NaN,No,Yes,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5474,Male,United States,35.0,Employed full-time,NaN,NaN,No,Yes,Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5483,Male,United States,32.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5494,Male,United States,18.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5507,Male,United States,29.0,Employed full-time,NaN,NaN,No,Yes,Scientist/Researcher,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5520,Male,United States,20.0,Employed part-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5528,Male,United States,48.0,Employed full-time,NaN,NaN,No,Yes,Scientist/Researcher,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5534,Male,United States,35.0,Employed full-time,NaN,NaN,No,Yes,Data Analyst,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5551,Female,United States,NaN,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,Somewhat important,Somewhat important,Somewhat important,Not important,Somewhat important,Not important,Very Important,Very Important,Very Important,Somewhat important
5571,Male,United States,27.0,Employed full-time,NaN,NaN,No,Yes,Programmer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5578,Male,United States,35.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5579,Female,United States,27.0,Employed full-time,NaN,NaN,No,Yes,Operations Research Practitioner,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5580,Female,United States,30.0,Employed full-time,NaN,NaN,No,Yes,Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5590,Male,United States,37.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5596,Male,United States,29.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5616,Male,United States,40.0,Employed full-time,NaN,NaN,No,Yes,Data Analyst,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5631,Male,United States,26.0,Employed full-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5641,Male,United States,59.0,Employed part-time,NaN,NaN,No,Yes,Other,Perfectly,...,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Not important,Very Important,Not important,Somewhat important,Not important
5656,Female,United States,26.0,Employed full-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5667,Male,United States,57.0,Employed full-time,NaN,NaN,No,Yes,Other,Fine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5669,Male,United States,36.0,Employed full-time,NaN,NaN,No,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5676,Female,United States,26.0,Employed full-time,NaN,NaN,No,Yes,Other,Perfectly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5682,Male,United States,47.0,Employed part-time,NaN,NaN,No,Yes,Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5698,Female,United States,41.0,Employed full-time,NaN,NaN,No,Yes,Software Developer/Software Engineer,Poorly,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#Next Steps
#Look at specific career switcher data