In [100]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import stop_words

import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.tokenize import RegexpTokenizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline

In [101]:

custom_stopwords = ['000', '01', '06', '08','10254', '12', '15',
                   '19', '2018', '22', '25', '28', '45', '500',
                   'cox', 'norfolk', 'apply', 'com', 'www', 'applications', 'application',
                   'applicants', 'southern', 'https', 'ia', 'var', 'indeedapply', 'env',
                   'atlanta', 'opportunity', 'iip', 'gender', 'location', 'new', 'employer',
                   'midtown', 'manheim', 'ml', 'including', 'llc', 'truck', 'automotive', 'nationality', 
                   'nation', 'iot', 'kelley', 'hopea', 'date', 'incadea', 'honeywell', 'j00067915', '00', '10', 
                   '100', '16', '16614', '18', '18230', '1901', '20', '2006', '2013', '24', '27', '401', '40b',
                   '420', '450', '50', '60', 'kentucky'
                   
                   ]

In [107]:
# new list = default list stop_words.ENGLISH_STOP_WORDS
# new list.append(whatever)

# cvec = CountVectorizer(stop_words = new list)

new_stop = list(stop_words.ENGLISH_STOP_WORDS)

new_stop.extend(custom_stopwords)


cvec = CountVectorizer(stop_words = new_stop, min_df=10)

In [108]:
Para = pd.read_csv('Paragraphs')

In [109]:
Para['0'][6]

'Community / Marketing Title: Data Scientist'

`cvec.fit()` will be expecting a pandas Series of text objects:

In [110]:
cvec.fit(Para['0'])
new_corpus = cvec.transform(Para['0'])
new_corpus

<339x62 sparse matrix of type '<class 'numpy.int64'>'
	with 955 stored elements in Compressed Sparse Row format>

In [111]:
new_corpus.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [112]:
df2  = pd.DataFrame(new_corpus.todense(),
                   columns=cvec.get_feature_names())

df2.head()

df2.sort_values('data', ascending=False).head(10)

,analysis,analytics,applying,business,color,companies,company,customer,data,decision,...,test,time,tools,use,using,value,veteran,work,working,years
232,1,2,0,7,0,1,2,2,11,0,...,0,0,0,0,0,1,0,2,1,0
320,0,0,0,0,0,0,0,0,8,0,...,0,0,0,0,0,0,0,0,0,0
321,0,0,0,0,0,0,1,0,7,0,...,0,0,0,0,0,0,0,0,0,0
274,0,0,1,0,0,0,0,1,6,1,...,0,0,3,0,1,0,0,2,3,5
245,1,1,0,2,0,0,0,0,6,0,...,0,0,1,0,0,0,0,1,1,0
242,1,0,0,1,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
195,1,0,0,0,0,0,0,0,5,0,...,0,0,0,1,0,0,0,0,0,0
241,0,1,0,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,1,1,0
213,0,1,0,1,0,0,0,0,4,0,...,0,0,0,1,1,0,0,0,2,0
54,1,0,0,0,0,0,0,0,4,0,...,0,0,1,0,1,0,0,1,1,0

In [113]:
df2.sum().sort_values(ascending=False)

data              155
team               50
business           49
experience         41
scientist          35
analytics          34
work               32
job                30
skills             26
company            25
salary             24
solutions          23
value              23
research           22
working            20
learning           20
required           19
status             19
machine            19
role               17
position           17
technology         17
preferred          16
equal              16
science            16
tools              15
years              15
time               14
hiscox             14
information        14
                 ...
companies          14
join               13
analysis           13
technical          13
operations         12
applying           12
education          12
test               12
modeling           11
using              11
products           11
qualifications     11
decision           11
head               11
environment        11
ms                 10
color              10
use                10
veteran            10
strong             10
employees          10
statistics         10
disability         10
statistical        10
sexual             10
race               10
orientation        10
js                 10
national           10
origin             10
Length: 62, dtype: int64

In [114]:
#clean it up by importing STOP Words

from sklearn.feature_extraction import stop_words
 
print(stop_words.ENGLISH_STOP_WORDS)

frozenset({'anyway', 'might', 'whether', 'around', 'former', 'nine', 'go', 'me', 'them', 'are', 'everywhere', 'already', 'ours', 'some', 'anyhow', 'whose', 'yourselves', 'besides', 'at', 'everyone', 'to', 'again', 'being', 'may', 'thereafter', 'ltd', 'would', 'until', 'itself', 'back', 'if', 'via', 'across', 'first', 'with', 'has', 'others', 'seem', 'every', 'please', 'least', 'themselves', 'whoever', 'hereupon', 'nor', 'and', 'twenty', 'whenever', 'also', 'became', 'twelve', 'formerly', 'whereas', 'there', 'you', 'made', 'whole', 'each', 'be', 'much', 'nothing', 'namely', 'before', 'against', 'off', 'throughout', 'for', 'seeming', 'detail', 'him', 'his', 'it', 'hereby', 'inc', 'show', 'only', 're', 'of', 'fire', 'thus', 'thence', 'amoungst', 'anyone', 'meanwhile', 'whereupon', 'cry', 'anything', 'eleven', 'interest', 'had', 'keep', 'serious', 'mill', 'although', 'amount', 'latter', 'on', 'how', 'fill', 'all', 'everything', 'many', 'after', 'de', 'always', 'above', 'hasnt', 'move', 'next', 'seems', 'none', 'sixty', 'we', 'will', 'must', 'due', 'yet', 'co', 'own', 'whither', 'her', 'what', 'anywhere', 'con', 'down', 'another', 'somehow', 'that', 'moreover', 'few', 'but', 'full', 'during', 'become', 'or', 'along', 'bill', 'less', 'when', 'a', 'any', 'ourselves', 'more', 'an', 'enough', 'below', 'thru', 'do', 'who', 'can', 'somewhere', 'have', 'he', 'afterwards', 'several', 'their', 'through', 'eg', 'my', 'nowhere', 'couldnt', 'should', 'these', 'while', 'sometime', 'as', 'etc', 'those', 'beforehand', 'fifty', 'onto', 'because', 'other', 'ten', 'is', 'either', 'here', 'fifteen', 'by', 'front', 'often', 'latterly', 'been', 'amongst', 'thereupon', 'over', 'elsewhere', 'were', 'herein', 'nobody', 'out', 'one', 'well', 'seemed', 'upon', 'cant', 'perhaps', 'becoming', 'put', 'empty', 'no', 'whence', 'thereby', 'about', 'third', 'eight', 'almost', 'indeed', 'top', 'this', 'where', 'very', 'us', 'see', 'even', 'otherwise', 'alone', 'never', 'within', 'both', 'hereafter', 'most', 'beyond', 'un', 'still', 'last', 'found', 'than', 'except', 'together', 'could', 'from', 'ie', 'therefore', 'though', 'hundred', 'mostly', 'wherever', 'was', 'sometimes', 'whom', 'herself', 'i', 'noone', 'the', 'hers', 'bottom', 'now', 'wherein', 'six', 'without', 'forty', 'find', 'same', 'part', 'two', 'its', 'per', 'three', 'mine', 'side', 'sincere', 'whereby', 'done', 'not', 'something', 'why', 'our', 'take', 'five', 'such', 'among', 'someone', 'your', 'beside', 'once', 'nevertheless', 'hence', 'himself', 'rather', 'describe', 'in', 'get', 'four', 'further', 'since', 'behind', 'toward', 'thick', 'which', 'give', 'name', 'system', 'so', 'yours', 'too', 'up', 'she', 'neither', 'yourself', 'therein', 'under', 'becomes', 'myself', 'however', 'call', 'then', 'cannot', 'am', 'towards', 'else', 'thin', 'into', 'whatever', 'whereafter', 'between', 'they', 'ever'})

In [115]:
#save cleaned up dataframe

df2.to_csv('Cultural_Word_Rank')

In [116]:
df2 = pd.read_csv('Cultural_Word_Rank')

In [117]:
df2.sum().sort_values(ascending=False)

Unnamed: 0        57291
data                155
team                 50
business             49
experience           41
scientist            35
analytics            34
work                 32
job                  30
skills               26
company              25
salary               24
value                23
solutions            23
research             22
working              20
learning             20
machine              19
status               19
required             19
position             17
technology           17
role                 17
preferred            16
science              16
equal                16
years                15
tools                15
time                 14
hiscox               14
                  ...
develop              14
analysis             13
technical            13
join                 13
education            12
test                 12
operations           12
applying             12
environment          11
products             11
using                11
decision             11
qualifications       11
head                 11
modeling             11
use                  10
race                 10
veteran              10
sexual               10
statistical          10
color                10
orientation          10
national             10
js                   10
ms                   10
statistics           10
disability           10
strong               10
employees            10
origin               10
Length: 63, dtype: int64

In [118]:
df2

,Unnamed: 0,analysis,analytics,applying,business,color,companies,company,customer,data,...,test,time,tools,use,using,value,veteran,work,working,years
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,7,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,9,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,10,0,3,0,0,0,0,1,0,3,...,0,0,0,0,0,0,0,1,0,0
11,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,13,0,2,0,2,0,0,0,0,1,...,0,1,1,0,0,1,0,0,1,0
14,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,16,0,2,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
17,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,20,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,21,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,2,0,0,0,0
22,22,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,24,0,1,0,1,0,0,0,0,2,...,0,0,1,0,0,0,0,0,0,0
25,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,26,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
27,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,28,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,309,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
310,310,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
311,311,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
312,312,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
313,313,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
314,314,1,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
315,315,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
316,316,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
317,317,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
318,318,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
319,319,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
320,320,0,0,0,0,0,0,0,0,8,...,0,0,0,0,0,0,0,0,0,0
321,321,0,0,0,0,0,0,1,0,7,...,0,0,0,0,0,0,0,0,0,0
322,322,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,323,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
324,324,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325,325,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
326,326,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
327,327,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
328,328,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329,329,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
330,330,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
331,331,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
332,332,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
333,333,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,2,0,0,0,0
334,334,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
335,335,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
336,336,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
337,337,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
338,338,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [119]:
df2.iloc[:,0:10].sum()

Unnamed: 0    57291
analysis         13
analytics        34
applying         12
business         49
color            10
companies        14
company          25
customer         14
data            155
dtype: int64

In [120]:
CountVectorizer(min_df=1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [121]:
df2.sum().sort_values(ascending=True)

origin               10
employees            10
strong               10
disability           10
statistics           10
ms                   10
js                   10
national             10
orientation          10
color                10
statistical          10
sexual               10
veteran              10
race                 10
use                  10
modeling             11
head                 11
qualifications       11
decision             11
using                11
products             11
environment          11
applying             12
operations           12
test                 12
education            12
join                 13
technical            13
analysis             13
develop              14
                  ...
hiscox               14
time                 14
tools                15
years                15
equal                16
science              16
preferred            16
role                 17
technology           17
position             17
required             19
status               19
machine              19
learning             20
working              20
research             22
solutions            23
value                23
salary               24
company              25
skills               26
job                  30
work                 32
analytics            34
scientist            35
experience           41
business             49
team                 50
data                155
Unnamed: 0        57291
Length: 63, dtype: int64

In [122]:
list(df2.columns.values)

['Unnamed: 0',
 'analysis',
 'analytics',
 'applying',
 'business',
 'color',
 'companies',
 'company',
 'customer',
 'data',
 'decision',
 'develop',
 'disability',
 'education',
 'employees',
 'environment',
 'equal',
 'experience',
 'head',
 'hiscox',
 'information',
 'job',
 'join',
 'js',
 'learning',
 'machine',
 'modeling',
 'ms',
 'national',
 'operations',
 'orientation',
 'origin',
 'position',
 'preferred',
 'products',
 'qualifications',
 'race',
 'required',
 'research',
 'role',
 'salary',
 'science',
 'scientist',
 'sexual',
 'skills',
 'solutions',
 'statistical',
 'statistics',
 'status',
 'strong',
 'team',
 'technical',
 'technology',
 'test',
 'time',
 'tools',
 'use',
 'using',
 'value',
 'veteran',
 'work',
 'working',
 'years']

In [123]:
cultural_words = df2

In [124]:
cultural_words.columns

Index(['Unnamed: 0', 'analysis', 'analytics', 'applying', 'business', 'color',
       'companies', 'company', 'customer', 'data', 'decision', 'develop',
       'disability', 'education', 'employees', 'environment', 'equal',
       'experience', 'head', 'hiscox', 'information', 'job', 'join', 'js',
       'learning', 'machine', 'modeling', 'ms', 'national', 'operations',
       'orientation', 'origin', 'position', 'preferred', 'products',
       'qualifications', 'race', 'required', 'research', 'role', 'salary',
       'science', 'scientist', 'sexual', 'skills', 'solutions', 'statistical',
       'statistics', 'status', 'strong', 'team', 'technical', 'technology',
       'test', 'time', 'tools', 'use', 'using', 'value', 'veteran', 'work',
       'working', 'years'],
      dtype='object')

In [106]:
df2.sum().sort_values()[df2.sum().sort_values() > 10].index

Index(['world', 'qualifications', 'using', 'protected', 'modeling', 'head',
       'environment', 'responsible', 'products', 'decision', 'processes',
       'systems', 'education', 'test', 'operations', 'applying', 'join',
       'analysis', 'technical', 'customer', 'companies', 'develop',
       'information', 'time', 'hiscox', 'years', 'tools', 'equal', 'science',
       'preferred', 'role', 'technology', 'position', 'window', 'machine',
       'status', 'required', 'engineering', 'learning', 'working', 'research',
       'value', 'solutions', 'salary', 'company', 'skills', 'job', 'work',
       'analytics', 'scientist', 'document', 'experience', 'business', 'team',
       'data', 'Unnamed: 0'],
      dtype='object')