In [1]:
import re
import requests

import pandas as pd

from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline

In [2]:
# Raw Data
jd_df = pd.read_csv('Bullets')
resume_df = pd.read_csv('Baseline Resume-Cleaned.csv')

In [3]:
resume_df.shape

(76, 2)

In [9]:
resume_df = resume_df.drop(['0'], axis=1)

ValueError: labels ['0'] not contained in axis

In [10]:
resume_df

                                              Phone:
0                                   Email:.@gmail.com
1                         Reach me professionally at:
2     http://www.linkedin.com/pub/--mba-pmp/0/641/695
3                                        Tweet Me At:
4                                            @pmp4rpo
5                    Chronological Career Progression
6                              Data Scientist Student
7     General Assembly Data Science Immersive Program
8                                                2018
9   General Assembly provides courses in mobile an...
10   600 Hours of immersive data science training....
11     Course conducted almost exclusively in Python.
12                  Extensive use of Python libraries
13                                         Matplotlib
14                                       Scikit-Learn
15                                              Numpy
16                                             Pandas
17                                              PyMC3
18  Strong emphasis on machine learning throughout...
19  Worked on multiple lab projects whose emphasis...
20                     EDA (Exploratory Data Analysis
21                    Data Analysis and Visualization
22           Modeling and measuring model performance
23                   Tree Based Classification Models
24               Supervised and Unsupervised Learning
25                        Natural Language Processing
26  Capstone Project: Maximizing resume match perc...
27                   Senior Manager - Implementation
28                           Allegis Global Solutions
29                                          2014-2018
..                                                ...
46   Lead a recruitment team supporting multiple c...
47   Analyzed data provided by analytics team tide...
48   Presented proposals townership on strategic d...
49   Developed metrics and reports for global recr...
50                  Futurestep  A Korn /Ferry Company
51                                 Solution Architect
52                                          2003-2012
53                    Client: Cummins Diesel Engines
54                      Client: Fosters Wine Estates
55                                  Client: Wal-Mart
56  Project:  Client required a global ATS platfor...
57   Global implementation experience from plannin...
58   Lead the identification of stakeholders for t...
59   Lead business requirements meeting tunderstan...
60   Re-engineer and transform clients recruiting ...
61   Assisted in the configuration Talerecruiting ...
62   Created test scripts and scenarios. Led UAT (...
63   Defined reports based on client requirements ...
64   Developed and delivered Taletraining material...
65                       Education and Certifications
66                                   General Assembly
67                     Data Science Immersive Program
68                    Saint Marys College, California
69                         Executive Trans Global MBA
70             Saint Josephs University, Pennsylvania
71       BA International Relations; Minor Philosophy
72                       Project Management Institute
73               PMP  Project Management Professional
74                                           MBA, PMP
75                                               2018

[76 rows x 1 columns]

In [8]:
jd_df

                                                     0
0    Location, Location, Location - 1372 Peachtree ...
1    Competitive compensation with incentive opport...
2    Benefits include: Medical, Dental, Vision and ...
3    Becoming an integral part of a winning team su...
4    Supportive leadership that recognizes and rewa...
5    Small company culture where everyone’s contrib...
6    Ability to participate in a constant offering ...
7             Casual work environment and team outings
8    Experience joining a company at a high-growth,...
9    Collaborate with product management and engine...
10   Able to identify customers' needs and desires ...
11   Deliver informative and effective findings, re...
12   Create dashboards of important statistics and ...
13   Develop and implement scalable and efficient m...
14   Develop predictive models to address various b...
15   MS or PhD degree in Computer Science or releva...
16   Proficient in one or more programming language...
17   Familiar with one or more machine learning or ...
18   Knowledge and experience of machine learning, ...
19   Knowledge and experience of relational databas...
20   Strong analytical and quantitative problem-sol...
21   Experience with big data techniques (such as H...
22   Knowledge of cloud platforms (such as AWS or A...
23                                   Atlanta, GA 30309
24                                       United States
25   Analyzing, processing, evaluating and document...
26   Identifying/developing appropriate machine lea...
27   Prototyping tools and techniques to solve comp...
28   Developing data driven models to quantify the ...
29   Applying, modifying and inventing algorithms t...
..                                                 ...
858  A Bachelor's degree in Imaging Science, Electr...
859  A Master’s degree in Imaging Science, Electric...
860  A Doctoral degree in Imaging Science, Electric...
861   0-7 years of professional or graduate experience
862                         Satellite/Overhead imagery
863                  Geomatics/Geospatial Intelligence
864  Machine learning, pattern recognition, and clu...
865                                 Sensor data fusion
866                              EO/IR imaging systems
867                               Radiometric analysis
868                                     Fourier optics
869            Electro-optical/Image signal processing
870                             Point cloud processing
871  Lidar (i.e., topographic, bathymetric, atmosph...
872                        Hyperspectral imaging (HSI)
873          Analytic geometry and advanced statistics
874  Laboratory equipment such as oscilloscopes, sp...
875  Computational tools such as Matlab, Octave, an...
876    Programming languages such as Python and/or C++
877        Toolboxes such as CUDA, OpenGL, and Open CV
878                                             ArcGIS
879  Imaging Scientist Engineer Junior jobs in Atla...
880  Jobs at Georgia Tech Research Institute in Atl...
881  Imaging Scientist Engineer Junior salaries in ...
882  A Bachelor's degree in Aerospace, Computer, El...
883  A Master’s degree in Aerospace, Computer, Elec...
884  A Doctoral degree in Aerospace, Computer, Elec...
885                System Engineer jobs in Atlanta, GA
886  Jobs at Georgia Tech Research Institute in Atl...
887            System Engineer salaries in Atlanta, GA

[888 rows x 1 columns]

In [6]:
resume_df.shape

(76, 1)

In [7]:
resume_df

                                              Phone:
0                                   Email:.@gmail.com
1                         Reach me professionally at:
2     http://www.linkedin.com/pub/--mba-pmp/0/641/695
3                                        Tweet Me At:
4                                            @pmp4rpo
5                    Chronological Career Progression
6                              Data Scientist Student
7     General Assembly Data Science Immersive Program
8                                                2018
9   General Assembly provides courses in mobile an...
10   600 Hours of immersive data science training....
11     Course conducted almost exclusively in Python.
12                  Extensive use of Python libraries
13                                         Matplotlib
14                                       Scikit-Learn
15                                              Numpy
16                                             Pandas
17                                              PyMC3
18  Strong emphasis on machine learning throughout...
19  Worked on multiple lab projects whose emphasis...
20                     EDA (Exploratory Data Analysis
21                    Data Analysis and Visualization
22           Modeling and measuring model performance
23                   Tree Based Classification Models
24               Supervised and Unsupervised Learning
25                        Natural Language Processing
26  Capstone Project: Maximizing resume match perc...
27                   Senior Manager - Implementation
28                           Allegis Global Solutions
29                                          2014-2018
..                                                ...
46   Lead a recruitment team supporting multiple c...
47   Analyzed data provided by analytics team tide...
48   Presented proposals townership on strategic d...
49   Developed metrics and reports for global recr...
50                  Futurestep  A Korn /Ferry Company
51                                 Solution Architect
52                                          2003-2012
53                    Client: Cummins Diesel Engines
54                      Client: Fosters Wine Estates
55                                  Client: Wal-Mart
56  Project:  Client required a global ATS platfor...
57   Global implementation experience from plannin...
58   Lead the identification of stakeholders for t...
59   Lead business requirements meeting tunderstan...
60   Re-engineer and transform clients recruiting ...
61   Assisted in the configuration Talerecruiting ...
62   Created test scripts and scenarios. Led UAT (...
63   Defined reports based on client requirements ...
64   Developed and delivered Taletraining material...
65                       Education and Certifications
66                                   General Assembly
67                     Data Science Immersive Program
68                    Saint Marys College, California
69                         Executive Trans Global MBA
70             Saint Josephs University, Pennsylvania
71       BA International Relations; Minor Philosophy
72                       Project Management Institute
73               PMP  Project Management Professional
74                                           MBA, PMP
75                                               2018

[76 rows x 1 columns]

In [24]:
jd_df.rename(index=str, columns={"0": "Bullets"}, inplace = True)
#jd_df = jd_df.drop(['job_descriptions'], axis=1)
jd_df['Class'] = 'Job Description'

In [33]:
jd_df.columns = ['text', 'class']

In [ ]:
resume_df = pd.DataFrame(resume_df, columns=['resume'])

In [35]:
resume_df.columns = ['text', 'class']

In [36]:
# resume_df.rename(index=str, columns={"Phone: ": "Resume Desc"}, inplace = True)
# #jd_df = jd_df.drop(['job_descriptions'], axis=1)
# resume_df['Class'] = 'Baseline Resume'
# resume_df

In [37]:
combined_df = pd.concat([jd_df, resume_df], axis=0)

In [38]:
combined_df

                                                 text            class
0   Location, Location, Location - 1372 Peachtree ...  Job Description
1   Competitive compensation with incentive opport...  Job Description
2   Benefits include: Medical, Dental, Vision and ...  Job Description
3   Becoming an integral part of a winning team su...  Job Description
4   Supportive leadership that recognizes and rewa...  Job Description
5   Small company culture where everyone’s contrib...  Job Description
6   Ability to participate in a constant offering ...  Job Description
7            Casual work environment and team outings  Job Description
8   Experience joining a company at a high-growth,...  Job Description
9   Collaborate with product management and engine...  Job Description
10  Able to identify customers' needs and desires ...  Job Description
11  Deliver informative and effective findings, re...  Job Description
12  Create dashboards of important statistics and ...  Job Description
13  Develop and implement scalable and efficient m...  Job Description
14  Develop predictive models to address various b...  Job Description
15  MS or PhD degree in Computer Science or releva...  Job Description
16  Proficient in one or more programming language...  Job Description
17  Familiar with one or more machine learning or ...  Job Description
18  Knowledge and experience of machine learning, ...  Job Description
19  Knowledge and experience of relational databas...  Job Description
20  Strong analytical and quantitative problem-sol...  Job Description
21  Experience with big data techniques (such as H...  Job Description
22  Knowledge of cloud platforms (such as AWS or A...  Job Description
23                                  Atlanta, GA 30309  Job Description
24                                      United States  Job Description
25  Analyzing, processing, evaluating and document...  Job Description
26  Identifying/developing appropriate machine lea...  Job Description
27  Prototyping tools and techniques to solve comp...  Job Description
28  Developing data driven models to quantify the ...  Job Description
29  Applying, modifying and inventing algorithms t...  Job Description
..                                                ...              ...
46   Lead a recruitment team supporting multiple c...  Baseline Resume
47   Analyzed data provided by analytics team tide...  Baseline Resume
48   Presented proposals townership on strategic d...  Baseline Resume
49   Developed metrics and reports for global recr...  Baseline Resume
50                  Futurestep  A Korn /Ferry Company  Baseline Resume
51                                 Solution Architect  Baseline Resume
52                                          2003-2012  Baseline Resume
53                    Client: Cummins Diesel Engines   Baseline Resume
54                      Client: Fosters Wine Estates   Baseline Resume
55                                  Client: Wal-Mart   Baseline Resume
56  Project:  Client required a global ATS platfor...  Baseline Resume
57   Global implementation experience from plannin...  Baseline Resume
58   Lead the identification of stakeholders for t...  Baseline Resume
59   Lead business requirements meeting tunderstan...  Baseline Resume
60   Re-engineer and transform clients recruiting ...  Baseline Resume
61   Assisted in the configuration Talerecruiting ...  Baseline Resume
62   Created test scripts and scenarios. Led UAT (...  Baseline Resume
63   Defined reports based on client requirements ...  Baseline Resume
64   Developed and delivered Taletraining material...  Baseline Resume
65                       Education and Certifications  Baseline Resume
66                                   General Assembly  Baseline Resume
67                     Data Science Immersive Program  Baseline Resume
68                    Saint Marys College, California  Baseline Resume
69                         Executive Trans Global MBA  Baseline Resume
70             Saint Josephs University, Pennsylvania  Baseline Resume
71       BA International Relations; Minor Philosophy  Baseline Resume
72                       Project Management Institute  Baseline Resume
73               PMP  Project Management Professional  Baseline Resume
74                                           MBA, PMP  Baseline Resume
75                                               2018  Baseline Resume

[964 rows x 2 columns]

In [46]:
combined_df['class'].value_counts(normalize=True)

Job Description    0.921162
Baseline Resume    0.078838
Name: class, dtype: float64

In [40]:
X = combined_df['text']
y = combined_df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [41]:
pipe = Pipeline([
    ('cv', CountVectorizer()),
    ('lr', LogisticRegression())
])

pipe.fit(X_train, y_train)
pipe.score(X_train, y_train)

0.9820193637621023

In [42]:
pipe.score(X_test, y_test)

0.9087136929460581

In [43]:
test_report = pd.DataFrame({'sent': X_test, 'actual': y_test, 'preds': pipe.predict(X_test)})

In [49]:
pipe.predict_proba(X_test)

array([[4.92211600e-01, 5.07788400e-01],
       [4.06937062e-02, 9.59306294e-01],
       [2.22716923e-02, 9.77728308e-01],
       [3.22916718e-01, 6.77083282e-01],
       [1.12483842e-02, 9.88751616e-01],
       [1.00902381e-01, 8.99097619e-01],
       [3.62192658e-02, 9.63780734e-01],
       [6.56973186e-02, 9.34302681e-01],
       [1.83268328e-01, 8.16731672e-01],
       [6.99524452e-03, 9.93004755e-01],
       [4.08387583e-04, 9.99591612e-01],
       [9.53265626e-03, 9.90467344e-01],
       [1.48189586e-01, 8.51810414e-01],
       [7.54003438e-02, 9.24599656e-01],
       [3.09276410e-03, 9.96907236e-01],
       [1.08580494e-03, 9.98914195e-01],
       [2.07481737e-02, 9.79251826e-01],
       [2.26126841e-02, 9.77387316e-01],
       [9.91853107e-03, 9.90081469e-01],
       [2.28163114e-02, 9.77183689e-01],
       [2.88797037e-02, 9.71120296e-01],
       [8.31080712e-04, 9.99168919e-01],
       [3.17724018e-02, 9.68227598e-01],
       [2.40940236e-01, 7.59059764e-01],
       [6.92201057e-03, 9.93077989e-01],
       [3.10027481e-02, 9.68997252e-01],
       [2.02925022e-02, 9.79707498e-01],
       [1.81621568e-03, 9.98183784e-01],
       [2.04334342e-03, 9.97956657e-01],
       [1.34452173e-02, 9.86554783e-01],
       [2.59852346e-01, 7.40147654e-01],
       [1.02245461e-02, 9.89775454e-01],
       [9.04836184e-03, 9.90951638e-01],
       [2.78152718e-04, 9.99721847e-01],
       [2.64036634e-04, 9.99735963e-01],
       [1.13516265e-01, 8.86483735e-01],
       [1.68266525e-02, 9.83173347e-01],
       [8.88245032e-03, 9.91117550e-01],
       [7.28995880e-03, 9.92710041e-01],
       [1.15528969e-02, 9.88447103e-01],
       [2.02354267e-01, 7.97645733e-01],
       [3.31666537e-02, 9.66833346e-01],
       [1.03210829e-01, 8.96789171e-01],
       [6.33620271e-03, 9.93663797e-01],
       [2.88656393e-02, 9.71134361e-01],
       [3.22916718e-01, 6.77083282e-01],
       [2.41185661e-03, 9.97588143e-01],
       [2.87042640e-02, 9.71295736e-01],
       [2.83950883e-02, 9.71604912e-01],
       [1.92752402e-01, 8.07247598e-01],
       [2.53427692e-02, 9.74657231e-01],
       [3.10027481e-02, 9.68997252e-01],
       [9.91853107e-03, 9.90081469e-01],
       [1.15543628e-02, 9.88445637e-01],
       [8.92275500e-03, 9.91077245e-01],
       [1.53836538e-01, 8.46163462e-01],
       [2.83950883e-02, 9.71604912e-01],
       [9.57773953e-03, 9.90422260e-01],
       [7.75884645e-02, 9.22411535e-01],
       [4.46929550e-01, 5.53070450e-01],
       [2.76607974e-02, 9.72339203e-01],
       [4.71447333e-02, 9.52855267e-01],
       [4.93541276e-02, 9.50645872e-01],
       [1.27190873e-02, 9.87280913e-01],
       [5.33996113e-02, 9.46600389e-01],
       [1.17649007e-01, 8.82350993e-01],
       [3.12728091e-03, 9.96872719e-01],
       [3.02701896e-03, 9.96972981e-01],
       [1.09506544e-02, 9.89049346e-01],
       [1.22292388e-02, 9.87770761e-01],
       [6.33602414e-03, 9.93663976e-01],
       [7.35951011e-03, 9.92640490e-01],
       [6.43671943e-01, 3.56328057e-01],
       [3.76477012e-02, 9.62352299e-01],
       [1.98545436e-01, 8.01454564e-01],
       [4.10989115e-02, 9.58901089e-01],
       [3.68432775e-01, 6.31567225e-01],
       [1.80549703e-04, 9.99819450e-01],
       [1.23203169e-02, 9.87679683e-01],
       [1.11065076e-03, 9.98889349e-01],
       [1.18259445e-03, 9.98817406e-01],
       [5.23786511e-03, 9.94762135e-01],
       [2.14848521e-02, 9.78515148e-01],
       [7.97391798e-02, 9.20260820e-01],
       [5.07138881e-02, 9.49286112e-01],
       [2.82265569e-01, 7.17734431e-01],
       [1.87115369e-02, 9.81288463e-01],
       [4.64157814e-07, 9.99999536e-01],
       [1.92752402e-01, 8.07247598e-01],
       [2.56622731e-01, 7.43377269e-01],
       [3.03405070e-01, 6.96594930e-01],
       [7.35951011e-03, 9.92640490e-01],
       [2.80031030e-02, 9.71996897e-01],
       [6.50434505e-02, 9.34956549e-01],
       [1.70557938e-02, 9.82944206e-01],
       [2.23160820e-01, 7.76839180e-01],
       [2.40695875e-04, 9.99759304e-01],
       [1.70927260e-02, 9.82907274e-01],
       [6.92201057e-03, 9.93077989e-01],
       [1.63864789e-02, 9.83613521e-01],
       [1.16855636e-02, 9.88314436e-01],
       [1.51864068e-02, 9.84813593e-01],
       [1.24995257e-02, 9.87500474e-01],
       [1.88273043e-01, 8.11726957e-01],
       [3.97879567e-02, 9.60212043e-01],
       [4.29128149e-03, 9.95708719e-01],
       [1.37491508e-02, 9.86250849e-01],
       [3.70041403e-02, 9.62995860e-01],
       [7.52505908e-04, 9.99247494e-01],
       [7.82012086e-04, 9.99217988e-01],
       [2.23213839e-01, 7.76786161e-01],
       [1.05370859e-03, 9.98946291e-01],
       [1.56225791e-01, 8.43774209e-01],
       [8.40178118e-02, 9.15982188e-01],
       [1.56847804e-01, 8.43152196e-01],
       [2.63546015e-02, 9.73645398e-01],
       [1.14709176e-02, 9.88529082e-01],
       [1.74273510e-01, 8.25726490e-01],
       [1.15436915e-02, 9.88456308e-01],
       [1.18553879e-01, 8.81446121e-01],
       [1.01145887e-02, 9.89885411e-01],
       [1.68266525e-02, 9.83173347e-01],
       [3.02522492e-02, 9.69747751e-01],
       [1.54366868e-03, 9.98456331e-01],
       [2.21450451e-02, 9.77854955e-01],
       [7.45855893e-03, 9.92541441e-01],
       [2.67412511e-03, 9.97325875e-01],
       [1.02245461e-02, 9.89775454e-01],
       [7.45093109e-02, 9.25490689e-01],
       [9.65662063e-03, 9.90343379e-01],
       [3.46605977e-02, 9.65339402e-01],
       [3.27266688e-01, 6.72733312e-01],
       [2.55818781e-02, 9.74418122e-01],
       [8.38743716e-02, 9.16125628e-01],
       [7.62752385e-02, 9.23724761e-01],
       [4.21174887e-03, 9.95788251e-01],
       [6.13976666e-02, 9.38602333e-01],
       [1.28488198e-02, 9.87151180e-01],
       [1.63689193e-01, 8.36310807e-01],
       [9.91277953e-05, 9.99900872e-01],
       [2.47876530e-01, 7.52123470e-01],
       [9.39557955e-03, 9.90604420e-01],
       [1.16855636e-02, 9.88314436e-01],
       [2.13363875e-01, 7.86636125e-01],
       [1.68510918e-01, 8.31489082e-01],
       [1.63613685e-02, 9.83638631e-01],
       [1.10909740e-02, 9.88909026e-01],
       [9.39557955e-03, 9.90604420e-01],
       [2.97001697e-01, 7.02998303e-01],
       [2.35339864e-02, 9.76466014e-01],
       [5.55714098e-01, 4.44285902e-01],
       [1.38386581e-03, 9.98616134e-01],
       [1.16855636e-02, 9.88314436e-01],
       [1.15500148e-02, 9.88449985e-01],
       [1.23203169e-02, 9.87679683e-01],
       [2.43443365e-02, 9.75655664e-01],
       [9.93835826e-04, 9.99006164e-01],
       [1.36321610e-01, 8.63678390e-01],
       [4.17442972e-01, 5.82557028e-01],
       [1.69105077e-02, 9.83089492e-01],
       [1.13811127e-03, 9.98861889e-01],
       [1.16855636e-02, 9.88314436e-01],
       [7.73513362e-03, 9.92264866e-01],
       [1.12483842e-02, 9.88751616e-01],
       [4.99716735e-04, 9.99500283e-01],
       [5.67032770e-02, 9.43296723e-01],
       [5.25076614e-02, 9.47492339e-01],
       [3.27863571e-02, 9.67213643e-01],
       [1.28488198e-02, 9.87151180e-01],
       [7.35951011e-03, 9.92640490e-01],
       [9.92388459e-03, 9.90076115e-01],
       [3.59533696e-02, 9.64046630e-01],
       [7.80261141e-02, 9.21973886e-01],
       [3.17724018e-02, 9.68227598e-01],
       [8.73394867e-02, 9.12660513e-01],
       [2.35339864e-02, 9.76466014e-01],
       [3.73977426e-03, 9.96260226e-01],
       [4.37463735e-02, 9.56253627e-01],
       [9.39557955e-03, 9.90604420e-01],
       [1.07396679e-02, 9.89260332e-01],
       [4.01860350e-03, 9.95981396e-01],
       [1.81974601e-02, 9.81802540e-01],
       [1.78727251e-01, 8.21272749e-01],
       [2.84235487e-02, 9.71576451e-01],
       [4.05220255e-02, 9.59477975e-01],
       [5.25321142e-02, 9.47467886e-01],
       [3.03405070e-01, 6.96594930e-01],
       [6.06078900e-02, 9.39392110e-01],
       [2.54484545e-01, 7.45515455e-01],
       [3.27966128e-03, 9.96720339e-01],
       [6.24875042e-02, 9.37512496e-01],
       [1.89870956e-03, 9.98101290e-01],
       [2.77396132e-04, 9.99722604e-01],
       [4.87977765e-03, 9.95120222e-01],
       [1.14506345e-03, 9.98854937e-01],
       [9.65662063e-03, 9.90343379e-01],
       [9.66910196e-04, 9.99033090e-01],
       [1.12483842e-02, 9.88751616e-01],
       [1.24894509e-02, 9.87510549e-01],
       [1.91299673e-03, 9.98087003e-01],
       [1.47180729e-02, 9.85281927e-01],
       [1.06162964e-02, 9.89383704e-01],
       [1.47766309e-02, 9.85223369e-01],
       [3.94400273e-02, 9.60559973e-01],
       [1.99053358e-02, 9.80094664e-01],
       [4.87828830e-01, 5.12171170e-01],
       [2.30866273e-02, 9.76913373e-01],
       [1.83268328e-01, 8.16731672e-01],
       [6.98070261e-03, 9.93019297e-01],
       [2.25562005e-03, 9.97744380e-01],
       [4.59117177e-03, 9.95408828e-01],
       [4.91341960e-03, 9.95086580e-01],
       [4.45384492e-03, 9.95546155e-01],
       [2.12904759e-03, 9.97870952e-01],
       [7.00113413e-04, 9.99299887e-01],
       [1.15528969e-02, 9.88447103e-01],
       [2.70567682e-02, 9.72943232e-01],
       [3.42068757e-02, 9.65793124e-01],
       [6.49949927e-02, 9.35005007e-01],
       [2.02592627e-03, 9.97974074e-01],
       [5.63227007e-02, 9.43677299e-01],
       [6.77782150e-03, 9.93222179e-01],
       [9.83574007e-02, 9.01642599e-01],
       [4.12597594e-03, 9.95874024e-01],
       [2.44493146e-03, 9.97555069e-01],
       [1.02420330e-02, 9.89757967e-01],
       [2.59852346e-01, 7.40147654e-01],
       [1.18193537e-01, 8.81806463e-01],
       [3.24313403e-01, 6.75686597e-01],
       [3.26034606e-02, 9.67396539e-01],
       [2.11530288e-02, 9.78846971e-01],
       [7.35951011e-03, 9.92640490e-01],
       [1.55814566e-02, 9.84418543e-01],
       [2.33235638e-02, 9.76676436e-01],
       [1.01275018e-01, 8.98724982e-01],
       [2.70052720e-03, 9.97299473e-01],
       [1.05680682e-01, 8.94319318e-01],
       [3.06961914e-03, 9.96930381e-01],
       [1.30269636e-02, 9.86973036e-01],
       [6.05486519e-01, 3.94513481e-01],
       [1.64937056e-02, 9.83506294e-01]])

In [44]:
test_report.head()

,actual,preds,sent
29,Baseline Resume,Job Description,2014-2018
417,Job Description,Job Description,data analyst in related field: 2 years
235,Job Description,Job Description,"Identifies, evaluates, and implements emerging..."
53,Baseline Resume,Job Description,Client: Cummins Diesel Engines
815,Job Description,Job Description,Analyze and model both structured and unstruct...

In [59]:
combined_df.to_csv('Combined', index=False)

In [60]:
df4 = pd.read_csv('Combined')

In [61]:
df4

                                                  text            class
0    Location, Location, Location - 1372 Peachtree ...  Job Description
1    Competitive compensation with incentive opport...  Job Description
2    Benefits include: Medical, Dental, Vision and ...  Job Description
3    Becoming an integral part of a winning team su...  Job Description
4    Supportive leadership that recognizes and rewa...  Job Description
5    Small company culture where everyone’s contrib...  Job Description
6    Ability to participate in a constant offering ...  Job Description
7             Casual work environment and team outings  Job Description
8    Experience joining a company at a high-growth,...  Job Description
9    Collaborate with product management and engine...  Job Description
10   Able to identify customers' needs and desires ...  Job Description
11   Deliver informative and effective findings, re...  Job Description
12   Create dashboards of important statistics and ...  Job Description
13   Develop and implement scalable and efficient m...  Job Description
14   Develop predictive models to address various b...  Job Description
15   MS or PhD degree in Computer Science or releva...  Job Description
16   Proficient in one or more programming language...  Job Description
17   Familiar with one or more machine learning or ...  Job Description
18   Knowledge and experience of machine learning, ...  Job Description
19   Knowledge and experience of relational databas...  Job Description
20   Strong analytical and quantitative problem-sol...  Job Description
21   Experience with big data techniques (such as H...  Job Description
22   Knowledge of cloud platforms (such as AWS or A...  Job Description
23                                   Atlanta, GA 30309  Job Description
24                                       United States  Job Description
25   Analyzing, processing, evaluating and document...  Job Description
26   Identifying/developing appropriate machine lea...  Job Description
27   Prototyping tools and techniques to solve comp...  Job Description
28   Developing data driven models to quantify the ...  Job Description
29   Applying, modifying and inventing algorithms t...  Job Description
..                                                 ...              ...
934   Lead a recruitment team supporting multiple c...  Baseline Resume
935   Analyzed data provided by analytics team tide...  Baseline Resume
936   Presented proposals townership on strategic d...  Baseline Resume
937   Developed metrics and reports for global recr...  Baseline Resume
938                  Futurestep  A Korn /Ferry Company  Baseline Resume
939                                 Solution Architect  Baseline Resume
940                                          2003-2012  Baseline Resume
941                    Client: Cummins Diesel Engines   Baseline Resume
942                      Client: Fosters Wine Estates   Baseline Resume
943                                  Client: Wal-Mart   Baseline Resume
944  Project:  Client required a global ATS platfor...  Baseline Resume
945   Global implementation experience from plannin...  Baseline Resume
946   Lead the identification of stakeholders for t...  Baseline Resume
947   Lead business requirements meeting tunderstan...  Baseline Resume
948   Re-engineer and transform clients recruiting ...  Baseline Resume
949   Assisted in the configuration Talerecruiting ...  Baseline Resume
950   Created test scripts and scenarios. Led UAT (...  Baseline Resume
951   Defined reports based on client requirements ...  Baseline Resume
952   Developed and delivered Taletraining material...  Baseline Resume
953                       Education and Certifications  Baseline Resume
954                                   General Assembly  Baseline Resume
955                     Data Science Immersive Program  Baseline Resume
956                    Saint Marys College, California  Baseline Resume
957                         Executive Trans Global MBA  Baseline Resume
958             Saint Josephs University, Pennsylvania  Baseline Resume
959       BA International Relations; Minor Philosophy  Baseline Resume
960                       Project Management Institute  Baseline Resume
961               PMP  Project Management Professional  Baseline Resume
962                                           MBA, PMP  Baseline Resume
963                                               2018  Baseline Resume

[964 rows x 2 columns]