In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import stop_words

cvec = CountVectorizer(stop_words = stop_words.ENGLISH_STOP_WORDS)

In [3]:
custom_stopwords = ['000', '01', '06', '08','10254', '12', '15',
                   '19', '2018', '22', '25', '28', '45', '500',
                   'cox', 'norfolk', 'apply', 'com', 'www', 'applications', 'application',
                   'applicants', 'southern', 'https', 'ia', 'var', 'indeedapply', 'env',
                   'atlanta', 'opportunity', 'iip', 'gender', 'location', 'new', 'employer',
                   'midtown', 'manheim', 'ml', 'including', 'llc', 'truck', 'automotive', 'nationality', 
                   'nation', 'iot', 'kelley', 'hopea', 'date', 'incadea', 'honeywell', '100', '1372', '27', '300',
                   '30308', '30309', '59', '60', '666', '715', '800', '850', '89', '90', 'ga', 'geo', 'genetic',
                    'mercedes', 'marta', 'lunch', 'familimarity', 'fitting', 'floors', 'furthermore', 'living', 
                    'make', 'members', 'family', 'req149533', 'requisition', 'freshman', 'sophomore', 'et', 'etc',
                    'etl', 'job', 'invest', 'member', 'eye', 'relocation', 'Unnamed', 'wework', 'yarn', 'yrs',
                    'test', 'intent', 'intermediete', 'key', 'inflection', 'informatica', 'way', 'recent', 'fewer',
                    'iteratively', 'joining', 'd3', 'bi', 'bs', 'alteryx', 'benz', 'ai', 'arcgis', 'talend', 'al',
                    'bus', 'cassandra', 'growing', 'growth', 'guidance', 'bigdata', 'bigquery', 'cotiviti', 
                    'councils', 'like', 'located', 'devops', 'usa', 'winning', 'ex', '2003', '2012', '2013', '2014',
                    '600', '641', '695', 'pub', 'alsincludes',
                   ]

In [4]:
new_stop = list(stop_words.ENGLISH_STOP_WORDS)

new_stop.extend(custom_stopwords)


cvec = CountVectorizer(stop_words = new_stop)

In [5]:
pd.read_csv('Baseline Resume-Cleaned.csv')
df = pd.read_csv('Baseline Resume-Cleaned.csv')

In [6]:
df.drop('0', axis=1, inplace = True)

In [7]:
df

                                              Phone:
0                                   Email:.@gmail.com
1                         Reach me professionally at:
2     http://www.linkedin.com/pub/--mba-pmp/0/641/695
3                                        Tweet Me At:
4                                            @pmp4rpo
5                    Chronological Career Progression
6                              Data Scientist Student
7     General Assembly Data Science Immersive Program
8                                                2018
9   General Assembly provides courses in mobile an...
10   600 Hours of immersive data science training....
11     Course conducted almost exclusively in Python.
12                  Extensive use of Python libraries
13                                         Matplotlib
14                                       Scikit-Learn
15                                              Numpy
16                                             Pandas
17                                              PyMC3
18  Strong emphasis on machine learning throughout...
19  Worked on multiple lab projects whose emphasis...
20                     EDA (Exploratory Data Analysis
21                    Data Analysis and Visualization
22           Modeling and measuring model performance
23                   Tree Based Classification Models
24               Supervised and Unsupervised Learning
25                        Natural Language Processing
26  Capstone Project: Maximizing resume match perc...
27                   Senior Manager - Implementation
28                           Allegis Global Solutions
29                                          2014-2018
..                                                ...
46   Lead a recruitment team supporting multiple c...
47   Analyzed data provided by analytics team tide...
48   Presented proposals townership on strategic d...
49   Developed metrics and reports for global recr...
50                  Futurestep  A Korn /Ferry Company
51                                 Solution Architect
52                                          2003-2012
53                    Client: Cummins Diesel Engines
54                      Client: Fosters Wine Estates
55                                  Client: Wal-Mart
56  Project:  Client required a global ATS platfor...
57   Global implementation experience from plannin...
58   Lead the identification of stakeholders for t...
59   Lead business requirements meeting tunderstan...
60   Re-engineer and transform clients recruiting ...
61   Assisted in the configuration Talerecruiting ...
62   Created test scripts and scenarios. Led UAT (...
63   Defined reports based on client requirements ...
64   Developed and delivered Taletraining material...
65                       Education and Certifications
66                                   General Assembly
67                     Data Science Immersive Program
68                    Saint Marys College, California
69                         Executive Trans Global MBA
70             Saint Josephs University, Pennsylvania
71       BA International Relations; Minor Philosophy
72                       Project Management Institute
73               PMP  Project Management Professional
74                                           MBA, PMP
75                                               2018

[76 rows x 1 columns]

In [8]:
# I had to rename the columns, because my single column was labeled "Phone: " - note the added space. 

df.rename(columns={'Phone: ': 'Text'}, inplace=True)

In [9]:
df.columns

Index(['Text'], dtype='object')

In [10]:
df

                                                 Text
0                                   Email:.@gmail.com
1                         Reach me professionally at:
2     http://www.linkedin.com/pub/--mba-pmp/0/641/695
3                                        Tweet Me At:
4                                            @pmp4rpo
5                    Chronological Career Progression
6                              Data Scientist Student
7     General Assembly Data Science Immersive Program
8                                                2018
9   General Assembly provides courses in mobile an...
10   600 Hours of immersive data science training....
11     Course conducted almost exclusively in Python.
12                  Extensive use of Python libraries
13                                         Matplotlib
14                                       Scikit-Learn
15                                              Numpy
16                                             Pandas
17                                              PyMC3
18  Strong emphasis on machine learning throughout...
19  Worked on multiple lab projects whose emphasis...
20                     EDA (Exploratory Data Analysis
21                    Data Analysis and Visualization
22           Modeling and measuring model performance
23                   Tree Based Classification Models
24               Supervised and Unsupervised Learning
25                        Natural Language Processing
26  Capstone Project: Maximizing resume match perc...
27                   Senior Manager - Implementation
28                           Allegis Global Solutions
29                                          2014-2018
..                                                ...
46   Lead a recruitment team supporting multiple c...
47   Analyzed data provided by analytics team tide...
48   Presented proposals townership on strategic d...
49   Developed metrics and reports for global recr...
50                  Futurestep  A Korn /Ferry Company
51                                 Solution Architect
52                                          2003-2012
53                    Client: Cummins Diesel Engines
54                      Client: Fosters Wine Estates
55                                  Client: Wal-Mart
56  Project:  Client required a global ATS platfor...
57   Global implementation experience from plannin...
58   Lead the identification of stakeholders for t...
59   Lead business requirements meeting tunderstan...
60   Re-engineer and transform clients recruiting ...
61   Assisted in the configuration Talerecruiting ...
62   Created test scripts and scenarios. Led UAT (...
63   Defined reports based on client requirements ...
64   Developed and delivered Taletraining material...
65                       Education and Certifications
66                                   General Assembly
67                     Data Science Immersive Program
68                    Saint Marys College, California
69                         Executive Trans Global MBA
70             Saint Josephs University, Pennsylvania
71       BA International Relations; Minor Philosophy
72                       Project Management Institute
73               PMP  Project Management Professional
74                                           MBA, PMP
75                                               2018

[76 rows x 1 columns]

In [11]:
df['Text'][0]

'Email:.@gmail.com'

In [12]:
df['Text']

0                                     Email:.@gmail.com
1                           Reach me professionally at:
2       http://www.linkedin.com/pub/--mba-pmp/0/641/695
3                                          Tweet Me At:
4                                              @pmp4rpo
5                      Chronological Career Progression
6                                Data Scientist Student
7       General Assembly Data Science Immersive Program
8                                                  2018
9     General Assembly provides courses in mobile an...
10     600 Hours of immersive data science training....
11       Course conducted almost exclusively in Python.
12                    Extensive use of Python libraries
13                                           Matplotlib
14                                         Scikit-Learn
15                                                Numpy
16                                               Pandas
17                                                PyMC3
18    Strong emphasis on machine learning throughout...
19    Worked on multiple lab projects whose emphasis...
20                       EDA (Exploratory Data Analysis
21                      Data Analysis and Visualization
22             Modeling and measuring model performance
23                     Tree Based Classification Models
24                 Supervised and Unsupervised Learning
25                          Natural Language Processing
26    Capstone Project: Maximizing resume match perc...
27                     Senior Manager - Implementation
28                             Allegis Global Solutions
29                                            2014-2018
                            ...
46     Lead a recruitment team supporting multiple c...
47     Analyzed data provided by analytics team tide...
48     Presented proposals townership on strategic d...
49     Developed metrics and reports for global recr...
50                    Futurestep  A Korn /Ferry Company
51                                   Solution Architect
52                                            2003-2012
53                      Client: Cummins Diesel Engines
54                        Client: Fosters Wine Estates
55                                    Client: Wal-Mart
56    Project:  Client required a global ATS platfor...
57     Global implementation experience from plannin...
58     Lead the identification of stakeholders for t...
59     Lead business requirements meeting tunderstan...
60     Re-engineer and transform clients recruiting ...
61     Assisted in the configuration Talerecruiting ...
62     Created test scripts and scenarios. Led UAT (...
63     Defined reports based on client requirements ...
64     Developed and delivered Taletraining material...
65                         Education and Certifications
66                                     General Assembly
67                       Data Science Immersive Program
68                      Saint Marys College, California
69                           Executive Trans Global MBA
70               Saint Josephs University, Pennsylvania
71         BA International Relations; Minor Philosophy
72                         Project Management Institute
73                 PMP  Project Management Professional
74                                             MBA, PMP
75                                                 2018
Name: Text, Length: 76, dtype: object

In [13]:
cvec.fit(df['Text'])
new_corpus = cvec.transform(df['Text'])
new_corpus

# cvec.fit(bullets['0'])
# new_corpus = cvec.transform(bullets['0'])
# new_corpus

<76x272 sparse matrix of type '<class 'numpy.int64'>'
	with 388 stored elements in Compressed Sparse Row format>

In [14]:
new_corpus.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [15]:
df  = pd.DataFrame(new_corpus.todense(),
                   columns=cvec.get_feature_names())

df.head()

df.sort_values('data', ascending=False).head(10)

,acceptance,access,accounting,allegis,alumni,analysis,analytical,analytics,analyzed,architect,...,vms,wal,web,weeks,wine,worked,workflow,workflows,writer,êgeneral
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.sum().sort_values(ascending=False)

data              11
global             8
client             8
implementation     8
management         6
clients            5
project            5
requirements       5
reports            5
recruiting         5
science            4
based              4
process            4
lead               4
business           4
general            3
pmp                3
immersive          3
course             3
team               3
technology         3
mba                3
consulting         3
analytics          3
assembly           3
manager            2
using              2
india              2
systems            2
hitachi            2
                  ..
party              1
pennsylvania       1
percentage         1
philosophy         1
required           1
relationships      1
relations          1
related            1
recommendation     1
reach              1
ranked             1
pymc3              1
providing          1
provides           1
provided           1
proposals          1
projects           1
progression        1
programs           1
professionally     1
professional       1
product            1
processing         1
president          1
presented          1
pmp4rpo            1
platform           1
planning           1
plan               1
acceptance         1
Length: 272, dtype: int64

In [17]:
df.to_csv('Resume_Vectorized.csv')

In [18]:
pd.read_csv('Resume_Vectorized.csv')

,Unnamed: 0,acceptance,access,accounting,allegis,alumni,analysis,analytical,analytics,analyzed,...,vms,wal,web,weeks,wine,worked,workflow,workflows,writer,êgeneral
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,9,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
10,10,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
11,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
20,20,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,21,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,26,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,28,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,46,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
47,47,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
48,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,49,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,50,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,51,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,52,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,53,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,54,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
55,55,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
56,56,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,57,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,58,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59,59,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
61,61,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62,62,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,63,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
64,64,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65,65,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
66,66,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,67,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
68,68,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70,70,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71,71,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72,72,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,73,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74,74,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,75,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0